main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import accounts.views
import shared.views
import users.views

urlpatterns = [
    path('', shared.views.index, name='index'),
    path('admin/', admin.site.urls),
    path('setlang/<str:langcode>/', shared.views.setlang, name='setlang'),
    path('django-rq/', include('django_rq.urls')),
    path('subjects/', include('subjects.urls')),
    path('users/<str:user_username>/', users.views.user_detail, name='user-detail'),
    path('user/', include('users.urls')),
    path('login/', accounts.views.user_login, name='login'),
    path('logout/', accounts.views.user_logout, name='logout'),
    path('signup/', accounts.views.user_signup, name='signup'),
    path('__reload__/', include('django_browser_reload.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subjects/urls.py
from django.urls import path, re_path

from . import views

app_name = 'subjects'

urlpatterns = [
    path('', views.subject_list, name='subject-list'),
    path('enroll/', views.enroll_subjects, name='enroll-subjects'),
    path('unenroll/', views.unenroll_subjects, name='unenroll-subjects'),
    path('certificate/', views.request_certificate, name='request-certificate'),
    re_path(
        '(?P<subject_code>[A-Z]{3})/lessons/(?P<lesson_pk>\d+)/edit/',
        views.edit_lesson,
        name='edit-lesson',
    ),
    re_path(
        '(?P<subject_code>[A-Z]{3})/lessons/(?P<lesson_pk>\d+)/delete/',
        views.delete_lesson,
        name='delete-lesson',
    ),
    re_path(
        '(?P<subject_code>[A-Z]{3})/lessons/(?P<lesson_pk>\d+)/',
        views.lesson_detail,
        name='lesson-detail',
    ),
    re_path(
        '(?P<subject_code>[A-Z]{3})/marks/edit/',
        views.edit_marks,
        name='edit-marks',
    ),
    re_path(
        '(?P<subject_code>[A-Z]{3})/marks/',
        views.mark_list,
        name='mark-list',
    ),
    re_path(
        '(?P<subject_code>[A-Z]{3})/lessons/add/',
        views.add_lesson,
        name='add-lesson',
    ),
    re_path(
        '(?P<subject_code>[A-Z]{3})/',
        views.subject_detail,
        name='subject-detail',
    ),
]

subjects/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse


class Enrollment(models.Model):
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='enrolled', on_delete=models.CASCADE
    )
    subject = models.ForeignKey(
        'subjects.Subject', related_name='enrollments', on_delete=models.CASCADE
    )
    enrolled_at = models.DateField(auto_now_add=True)
    mark = models.PositiveSmallIntegerField(
        blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(10)]
    )

    class Meta:
        ordering = ['student__last_name', 'student__first_name']

    def __str__(self):
        return f'{self.student} ({self.subject}) {self.mark}'


class Subject(models.Model):
    code = models.CharField(
        max_length=3,
        unique=True,
    )
    name = models.CharField(max_length=128)
    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='teacher_subjects',
        on_delete=models.PROTECT,
    )
    students = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='students_subjects',
        through=Enrollment,
    )

    def get_absolute_url(self):
        return reverse('subjects:subject-detail', kwargs={'subject_code': self.code})

    def __str__(self):
        return self.code


class Lesson(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField(blank=True)
    subject = models.ForeignKey(
        'subjects.Subject',
        related_name='lessons',
        on_delete=models.CASCADE,
    )

    def get_absolute_url(self):
        return reverse(
            'subjects:lesson-detail',
            kwargs={'subject_code': self.subject.code, 'lesson_pk': self.pk},
        )

    def __str__(self):
        return f'Title: {self.title}, Subject: {self.subject}'

subjects/forms.py
from crispy_bootstrap5.bootstrap5 import Field, FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Layout, Row, Submit
from django import forms

from .models import Enrollment, Lesson, Subject


class AddLessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = (
            'title',
            'content',
        )

    def __init__(self, subject, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.subject = subject
        self.helper = FormHelper()
        self.helper.attrs = dict(novalidate=True)
        self.helper.layout = Layout(
            FloatingField('title'),
            FloatingField('content'),
            Submit('submit', 'Submit', css_class='w-100 mt-2 mb-2'),
        )

    def save(self, *args, **kwargs):
        lesson = super().save(commit=False)
        lesson.subject = self.subject
        lesson = super().save(*args, **kwargs)
        return lesson


class EditLessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = (
            'title',
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'style': 'width: 100%; height: 300px;',
                    'class': 'form-control',
                    'placeholder': 'Escribe el contenido aquí...',
                }
            ),
        }

    def __init__(self, subject, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.subject = subject
        self.helper = FormHelper()
        self.helper.attrs = dict(novalidate=True)
        self.helper.layout = Layout(
            FloatingField('title'),
            FloatingField('content'),
            Submit('submit', 'Submit', css_class='w-100 mt-2 mb-2'),
        )


class EditMarkForm(forms.ModelForm):
    class Meta:
        model = Enrollment
        fields = ['mark']


class EditMarkFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_show_labels = False
        self.layout = Layout(
            Row(
                HTML(
                    '{% load subject_extras %} <div class="col-md-5">{% student_label formset forloop.counter0 %}</div>'
                ),
                Field('mark', wrapper_class='col-md-2'),
                css_class='align-items-baseline',
            )
        )
        self.add_input(Submit('save', 'Save marks', css_class='mt-3'))


class EnrollSubjectsForm(forms.Form):
    subjects = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

        enrolled_subjects = Enrollment.objects.filter(student=user).values_list(
            'subject', flat=True
        )
        self.fields['subjects'].queryset = Subject.objects.exclude(id__in=enrolled_subjects)

    def save(self, user):
        subjects_to_enroll = self.cleaned_data['subjects']
        for subject in subjects_to_enroll:
            Enrollment.objects.create(student=user, subject=subject)


class UnenrollSubjectsForm(forms.Form):
    subjects = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

        enrolled_subjects = Enrollment.objects.filter(student=user).values_list(
            'subject', flat=True
        )
        self.fields['subjects'].queryset = Subject.objects.filter(id__in=enrolled_subjects)

    def save(self, user):
        subjects_to_unenroll = self.cleaned_data['subjects']
        Enrollment.objects.filter(student=user, subject__in=subjects_to_unenroll).delete()

subjects/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render
from django.urls import reverse

from shared.decorators import enrolled_required, student_required, teacher_required

from .forms import (
    AddLessonForm,
    EditLessonForm,
    EditMarkForm,
    EditMarkFormSetHelper,
    EnrollSubjectsForm,
    UnenrollSubjectsForm,
)
from .models import Enrollment, Subject
from .tasks import deliver_certificate


@login_required
def subject_list(request):
    user = request.user
    profile = user.profile
    certificate_ready = False

    if profile.is_student():
        subjects = user.students_subjects.all()
        certificate_ready = not Enrollment.objects.filter(
            student=user, subject__in=subjects, mark__isnull=True
        ).exists()
    else:
        subjects = user.teacher_subjects.all()
    return render(
        request,
        'subjects/subject_list.html',
        dict(
            subjects=subjects,
            certificate_ready=certificate_ready,
        ),
    )


@enrolled_required
@login_required
def subject_detail(request, subject_code: str):
    user = request.user
    profile = user.profile

    if profile.is_student():
        subject = user.students_subjects.get(code=subject_code)
        enrollment = subject.enrollments.get(student=user)
    else:
        subject = user.teacher_subjects.get(code=subject_code)
        enrollment = False

    lessons = subject.lessons.all()

    return render(
        request,
        'subjects/subject_detail.html',
        dict(
            subject=subject,
            lessons=lessons,
            enrollment=enrollment,
        ),
    )


@enrolled_required
@login_required
def lesson_detail(request, subject_code: str, lesson_pk: int):
    subject = Subject.objects.get(code=subject_code)
    lesson = subject.lessons.get(pk=lesson_pk)

    return render(
        request,
        'lessons/lesson_detail.html',
        dict(
            subject=subject,
            lesson=lesson,
        ),
    )


@teacher_required
@login_required
def add_lesson(request, subject_code: str):
    subject = Subject.objects.get(code=subject_code)
    if request.method == 'GET':
        form = AddLessonForm(subject)
    else:
        if (form := AddLessonForm(subject, data=request.POST)).is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Lesson was successfully added.')
            return redirect(subject)
    return render(request, 'lessons/add_lesson.html', dict(form=form))


@teacher_required
@login_required
def edit_lesson(request, subject_code: str, lesson_pk: int):
    subject = Subject.objects.get(code=subject_code)
    lesson = subject.lessons.get(pk=lesson_pk)
    if request.method == 'GET':
        form = EditLessonForm(subject, instance=lesson)
    else:
        if (form := EditLessonForm(subject, data=request.POST, instance=lesson)).is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Changes were successfully saved.')
    return render(
        request,
        'lessons/edit_lesson.html',
        dict(form=form, subject=subject, lesson=lesson),
    )


@teacher_required
@login_required
def delete_lesson(request, subject_code: str, lesson_pk: int):
    subject = Subject.objects.get(code=subject_code)
    lesson = subject.lessons.get(pk=lesson_pk)

    lesson.delete()
    messages.add_message(request, messages.INFO, 'Lesson was successfully deleted.')
    return redirect(subject)


@teacher_required
@login_required
def mark_list(request, subject_code: str):
    subject = Subject.objects.get(code=subject_code)
    queryset = subject.enrollments.all()
    return render(
        request,
        'subjects/marks/mark_list.html',
        dict(subject=subject, enrollments=queryset),
    )


@teacher_required
@login_required
def edit_marks(request, subject_code: str):
    subject = Subject.objects.get(code=subject_code)

    MarkFormSet = modelformset_factory(Enrollment, EditMarkForm, extra=0)
    queryset = subject.enrollments.all()
    if request.method == 'POST':
        if (formset := MarkFormSet(queryset=queryset, data=request.POST)).is_valid():
            formset.save()
            messages.add_message(request, messages.SUCCESS, 'Marks were successfully saved.')
            return redirect(reverse('subjects:edit-marks', kwargs={'subject_code': subject_code}))
    else:
        formset = MarkFormSet(queryset=queryset)
    helper = EditMarkFormSetHelper()
    return render(
        request,
        'subjects/marks/edit_marks.html',
        dict(subject=subject, formset=formset, helper=helper),
    )


@student_required
@login_required
def enroll_subjects(request):
    if not hasattr(request.user, 'profile') or request.user.profile.role != 'S':
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = EnrollSubjectsForm(request.POST, user=request.user)
        if form.is_valid():
            form.save(user=request.user)
            messages.success(request, 'Successfully enrolled in the chosen subjects.')
            return redirect('subjects:subject-list')

    else:
        form = EnrollSubjectsForm(user=request.user)

    return render(
        request,
        'subjects/enroll_subjects.html',
        {'form': form},
    )


@student_required
@login_required
def unenroll_subjects(request):
    if not hasattr(request.user, 'profile') or request.user.profile.role != 'S':
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = UnenrollSubjectsForm(request.POST, user=request.user)
        if form.is_valid():
            form.save(user=request.user)
            messages.success(request, 'Successfully unenrolled from the chosen subjects.')
            return redirect('subjects:subject-list')

    else:
        form = UnenrollSubjectsForm(user=request.user)

    return render(
        request,
        'subjects/unenroll_subjects.html',
        {'form': form},
    )


@student_required
@login_required
def request_certificate(request):
    if request.user.enrolled.filter(mark__isnull=True).count() == 0:
        base_url = request.build_absolute_uri('/')
        deliver_certificate.delay(base_url, request)
        message = f'You will get the grade certificate quite soon at {request.user.email}'
        return render(
            request,
            'subjects/marks/certificate_confirmation.html',
            dict(
                message=message,
            ),
        )
    else:
        messages.error(request, 'You do not have permission to access this resource.')
        return HttpResponseForbidden()

subjects/templates/subjects/enroll_subjects.html
{% extends 'base.html' %}

{% block content %}
  <h2>Enroll in Subjects</h2>

  {% if messages %}
    <div class="alert alert-info">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="id_subjects">Choose subjects to enroll in:</label>
      {{ form.subjects }}
    </div>

    <button type="submit" class="btn btn-primary">Enroll</button>

    {% if form.errors %}
      <div class="alert alert-danger">
        <strong>There were errors in the form. Please fix them and try again.</strong>
      </div>
    {% endif %}
  </form>
{% endblock %}

subjects/templates/subjects/subject_detail.html
{% extends "base.html" %}

{% block title %} | {{ subject.code }}{% endblock %}

{% block content %}
  {% include "navbar.html" %}
  <nav aria-label="breadcrumb" style="margin-top: 70px; --bs-breadcrumb-divider: '>';">
    <ol class="breadcrumb">
      <li class="breadcrumb-item ms-2">
        <a href="{% url "subjects:subject-list" %}" class="link-offset-2 link-underline link-underline-opacity-0">
          Subjects
        </a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        {{ subject.code }}
      </li>
    </ol>
  </nav>
  <div class="container">
    <div class="list-group">
      <div class="list-group-item">
        <h5 class="mb-1">{{ subject.code }} // {{ subject.name }}</h5>
        <p class="mt-3">
          Subject taught by: {{ subject.teacher.get_full_name }} || <strong>{{ subject.teacher.get_username }}</strong>
        </p>
        {% if lessons %}
          {% if not user.profile.is_student %}
            <a href="{% url "subjects:add-lesson" subject.code %}" class="btn btn-primary"><i class="bi bi-file-earmark-plus-fill"></i> Add a new lesson</a>
          {% endif %}
        {% endif %}
        {% if enrollment.mark %}
          <div class="alert alert-info" role="alert">
            Your mark for this subject: <strong>{{ enrollment.mark }}</strong>
          </div>
        {% endif %}
        {% if not user.profile.is_student %}
        <a href="{% url "subjects:mark-list" subject.code %}" class="ms-3 btn btn-success">
          <i class="bi bi-box-arrow-up-right"></i> Marks
        </a>
        {% endif %}
      </div>
      {% if messages %}
        <div class="alert alert-info">
          {% for message in messages %}
            <p>{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}
      {% for lesson in lessons %}
        <div class="list-group-item d-flex justify-content-between align-items-center">
          {{ lesson.title }}
          <div>
            <a href="{% url 'subjects:lesson-detail' subject.code lesson.pk %}" class="ms-3 btn btn-info">
              <i class="bi bi-box-arrow-up-right"></i> View
            </a>
            {% if not user.profile.is_student %}
              <a href="{% url 'subjects:edit-lesson' subject.code lesson.pk %}" class="ms-3 btn btn-warning">
                <i class="bi bi-pencil-square"></i> Edit
              </a>
              <a href="{% url 'subjects:delete-lesson' subject.code lesson.pk %}" class="ms-3 btn btn-danger">
                <i class="bi bi-trash3"></i> Delete
              </a>
            {% endif %}
          </div>
        </div>      
      {% empty %}
        <div class="alert alert-warning" role="alert">
          This subject doesn't have any lessons yet.
          {% if not user.profile.is_student %}
            <a href="{% url "subjects:add-lesson" subject.code %}">Add a new lesson</a>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

subjects/templates/subjects/subject_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  {% include "navbar.html" %}
  <div class="container"style="margin-top: 70px;">
    {% if messages %}
      <div class="alert alert-info">
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %}
      </div>
    {% endif %}
    <h4>{% translate 'My Subjects' %}</h4>
    {% if subjects %}
      {% if user.profile.is_student %}
        <a href="{% url "subjects:enroll-subjects" %}" class="btn btn-success mb-3 mt-3">Enroll</a>
        <a href="{% url "subjects:unenroll-subjects" %}" class="btn btn-danger mb-3 mt-3">Unenroll</a>
        {% if certificate_ready %}
          <a href="{% url "subjects:request-certificate"%}" class="btn btn-info mb-3 mt-3">Request Mark Certificate</a>
        {% endif %}
      {% endif %}
    {% endif %}
    <div class="list-group">
      {% for subject in subjects %}
        <div class="list-group-item d-flex justify-content-between align-items-center">
          <div>
            <h5 class="mb-1">Code: {{ subject.code }}</h5>
            <p class="mb-1">Name: {{ subject.name }}</p>
          </div>
          <div>
            <a href="{{ subject.get_absolute_url }}" class="ms-3 btn btn-info">
              <i class="bi bi-box-arrow-up-right"></i> View
            </a>
          </div>
        </div>
      {% empty %}
        {% if user.profile.is_student %}
          <div class="alert alert-warning" role="alert">
            You are not yet enrolled in any subject 
            <a href="{% url "subjects:enroll-subjects" %}" class="alert-link">Enroll in one or more of our subjects here!</a>
            <a href="{% url "subjects:unenroll-subjects" %}" class="btn btn-danger" hidden>Unenroll</a>
          </div>
        {% else %}
          <div class="alert alert-warning" role="alert">
            You are not teaching any subject yet.
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

subjects/templates/subjects/unenroll_subjects.html
{% extends 'base.html' %}

{% block content %}
  <h2>Unenroll from Subjects</h2>

  {% if messages %}
    <div class="alert alert-info">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subjects">Choose subjects to unenroll from:</label>
      {{ form.subjects }}
    </div>

    <button type="submit" class="btn btn-primary">Unenroll</button>
  </form>

  {% if form.errors %}
    <div class="alert alert-danger">
      <strong>There were errors in the form. Please fix them and try again.</strong>
    </div>
  {% endif %}
{% endblock %}