main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import accounts.views
import shared.views
import users.views

urlpatterns = [
    path('', shared.views.index, name='index'),
    path('admin/', admin.site.urls),
    path('setlang/<str:langcode>/', shared.views.setlang, name='setlang'),
    path('django-rq/', include('django_rq.urls')),
    path('subjects/', include('subjects.urls')),
    path('users/<str:user_username>/', users.views.user_detail, name='user-detail'),
    path('user/', include('users.urls')),
    path('login/', accounts.views.user_login, name='login'),
    path('logout/', accounts.views.user_logout, name='logout'),
    path('signup/', accounts.views.user_signup, name='signup'),
    path('__reload__/', include('django_browser_reload.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('edit/', views.edit_profile, name='edit-profile'),
    path('leave/', views.leave, name='leave'),
]

users/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Profile(models.Model):
    class Role(models.TextChoices):
        STUDENT = 'S', 'Student'
        TEACHER = 'T', 'Teacher'

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    role = models.CharField(
        max_length=1,
        choices=Role,
        default=Role.STUDENT,
    )
    bio = models.TextField(blank=True)
    avatar = models.ImageField(
        upload_to='avatars',
        default='avatars/noavatar.png',
    )

    def get_absolute_url(self):
        return reverse('user-detail', kwargs={'user_username': self.user.username})

    def is_student(self):
        return self.role == self.Role.STUDENT

    def get_role(self):
        return self.get_role_display()

    def __str__(self):
        return f'User: {self.user}, Role: {self.role}'

users/forms.py
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django import forms

from .models import Profile


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'bio')
        widgets = {
            'bio': forms.Textarea(
                attrs={
                    'style': 'width: 100%; height: 350px;',
                    'class': 'form-control',
                    'placeholder': 'Enter your bio here...',
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.attrs = dict(novalidate=True, enctype='multipart/form-data')
        self.helper.layout = Layout(
            'avatar',
            FloatingField('bio'),
            Submit('submit', 'Save', css_class='w-100 mt-2 mb-2'),
        )

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from shared.decorators import student_required

from .forms import EditProfileForm


@login_required
def user_detail(request, user_username):
    user = User.objects.get(username=user_username)
    return render(
        request,
        'users/profile_detail.html',
        dict(
            user=user,
        ),
    )


@login_required
def edit_profile(request):
    user = User.objects.get(username=request.user.username)
    profile = user.profile

    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'User profile has been successfully saved.')
            return redirect(profile)
        else:
            messages.error(request, 'Error updating the profile. Please check the form.')

    else:
        form = EditProfileForm(instance=profile)

    return render(
        request,
        'users/edit_profile.html',
        {'form': form, 'profile': profile},
    )


@student_required
@login_required
def leave(request):
    user = request.user
    user.delete()
    messages.success(request, 'Good bye! Hope to see you soon.')

    return redirect('/')

users/templates/users/edit_profile.html
{% extends "base.html" %}
{% block app %}Users{% endblock %}{% block title %} | Edit Profile{% endblock %}
{% block content %}
  {% include "navbar.html" %}
  <nav aria-label="breadcrumb" style="margin-top: 70px; --bs-breadcrumb-divider: '>';">
    <ol class="breadcrumb">
      <li class="breadcrumb-item ms-2 text-muted">Users</li>
      <li class="breadcrumb-item ms-2">
        <a href="{% url "user-detail" user.username %}"><strong>{{ user.username }}'s</strong> Profile</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
  </nav>
  {% load crispy_forms_tags %}
  {% if messages %}
    <div class="alert alert-info">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
  <div class="row justify-content-center mt-5">
    <div class="col-md-4">
      <div class="card border-dark">
        <h4 class="card-header">
          Edit lesson
        </h4>
        <div class="card-body">
          {% crispy form %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/profile_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block app %}Users{% endblock %}{% block title %} | {{ user.username }}{% endblock %}

{% block content %}
    {% include "navbar.html" %}
    <nav aria-label="breadcrumb" style="margin-top: 70px; --bs-breadcrumb-divider: '>';">
        <ol class="breadcrumb">
            <li class="breadcrumb-item ms-2">Users</li>
            <li class="breadcrumb-item active" aria-current="page"><strong>{{ user.username }}'s</strong> Profile</li>
        </ol>
    </nav>
    {% if messages %}
        <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
        </div>
    {% endif %}
    <div class="card mt-4 shadow-sm border-0 rounded-3 d-flex flex-column">
        <div class="card-body d-flex align-items-center gap-4 p-4 flex-grow-1">
            {% if user.profile.avatar %}
                {% thumbnail user.profile.avatar "200x200" crop="center" format="PNG" as avatar %}
                    <img src="{{ avatar.url }}" alt="Thumbnail profile avatar" style="border-radius: 10px;">
                {% endthumbnail %}
            {% else %}
                <div class="d-flex justify-content-center align-items-center bg-light rounded-circle" style="width: 150px; height: 150px;">
                    <p class="text-muted mb-0" style="font-size: 14px;">No avatar</p>
                </div>
            {% endif %}
            <div class="flex-grow-1">
                <h5 class="m-0 text-dark" style="font-size: 20px; font-weight: 600;">{{ user.username }}</h5>
                <p class="mt-2 mb-2 text-muted" style="font-size: 14px;">
                    <strong>Full Name:</strong> {{ user.first_name }} {{ user.last_name }}
                </p>
                <p class="mb-2 text-muted" style="font-size: 14px;">
                    <strong>Email:</strong> {{ user.email }}
                </p>
                <p class="mb-2 text-muted" style="font-size: 14px;">
                    <strong>Role:</strong> {{ user.profile.get_role }}
                </p>
                <p class="mb-0 text-muted text-justify" style="font-size: 14px; line-height: 1.6; text-align: justify !important;">
                    {{ user.profile.bio|default:"This user has not added a bio yet." }}
                </p>                
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:edit-profile' %}" class="btn btn-warning">Edit Profile</a>
            {% if user.profile.is_student %}
                <a href="{% url 'users:leave' %}" class="btn btn-danger">Leave</a>
            {% endif %}
        </div>
    </div>
{% endblock %}